#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR/.."
source "$SCRIPT_DIR/../config.env"

echo "=== Publish Piper TTS Model to Hugging Face ==="
echo ""

# --- Step 1: Check for model files ---
MODEL_DIR="${PROJECT_DIR}/model"
ONNX_FILE="${MODEL_DIR}/${ONNX_NAME}.onnx"
CONFIG_FILE="${MODEL_DIR}/${ONNX_NAME}.onnx.json"

if [ ! -f "${ONNX_FILE}" ]; then
    echo "ERROR: Model file not found: ${ONNX_FILE}"
    echo ""
    echo "Either export locally with scripts/export.sh, or download from S3:"
    echo "  mkdir -p model"
    echo "  aws s3 cp s3://${S3_BUCKET}/${S3_CHECKPOINT_PREFIX}/exported/${ONNX_NAME}.onnx model/"
    echo "  aws s3 cp s3://${S3_BUCKET}/${S3_CHECKPOINT_PREFIX}/exported/${ONNX_NAME}.onnx.json model/"
    exit 1
fi

if [ ! -f "${CONFIG_FILE}" ]; then
    echo "ERROR: Config file not found: ${CONFIG_FILE}"
    exit 1
fi

echo "Model files found:"
echo "  ${ONNX_FILE} ($(du -h "${ONNX_FILE}" | cut -f1 | xargs))"
echo "  ${CONFIG_FILE}"

# Collect sample wav files
SAMPLE_WAVS=()
for wav in "${MODEL_DIR}"/test_*.wav; do
    [ -f "$wav" ] && SAMPLE_WAVS+=("$wav")
done
if [ ${#SAMPLE_WAVS[@]} -gt 0 ]; then
    echo "  ${#SAMPLE_WAVS[@]} sample wav file(s)"
fi
echo ""

# --- Step 2: Check huggingface-cli ---
if ! command -v huggingface-cli &>/dev/null; then
    echo "huggingface-cli not found. Installing huggingface_hub ..."
    pip install -q huggingface_hub
    echo ""
fi

# --- Step 3: Check authentication ---
if ! huggingface-cli whoami &>/dev/null; then
    echo "Not logged in to Hugging Face."
    echo "You need an access token from: https://huggingface.co/settings/tokens"
    echo ""
    huggingface-cli login
    echo ""
fi

HF_USER=$(huggingface-cli whoami 2>/dev/null | head -1)
echo "Logged in as: ${HF_USER}"
echo ""

# --- Step 4: Choose repo name ---
DEFAULT_REPO="${HF_USER}/piper-${LANG_LOCALE}-${PIPER_QUALITY}"
read -rp "Hugging Face repo [${DEFAULT_REPO}]: " HF_REPO
HF_REPO="${HF_REPO:-$DEFAULT_REPO}"
echo ""

# --- Step 5: Create repo ---
echo "Creating repo: ${HF_REPO} ..."
huggingface-cli repo create "${HF_REPO#*/}" --type model -y 2>/dev/null || true
echo ""

# --- Step 6: Prepare upload directory ---
UPLOAD_DIR=$(mktemp -d)
trap "rm -rf ${UPLOAD_DIR}" EXIT

cp "${ONNX_FILE}" "${UPLOAD_DIR}/"
cp "${CONFIG_FILE}" "${UPLOAD_DIR}/"

# Copy sample wavs
for wav in "${SAMPLE_WAVS[@]}"; do
    cp "$wav" "${UPLOAD_DIR}/samples/$(basename "$wav")" 2>/dev/null || {
        mkdir -p "${UPLOAD_DIR}/samples"
        cp "$wav" "${UPLOAD_DIR}/samples/$(basename "$wav")"
    }
done

# --- Step 7: Generate model card ---
# Build sample widget entries
WIDGET_YAML=""
for wav in "${SAMPLE_WAVS[@]}"; do
    BASENAME=$(basename "$wav" .wav)
    # Convert test_nice_day -> "Nice day"
    TITLE=$(echo "${BASENAME#test_}" | tr '_' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')
    WIDGET_YAML="${WIDGET_YAML}
  - src: samples/$(basename "$wav")
    example_title: \"${TITLE}\""
done

cat > "${UPLOAD_DIR}/README.md" <<MODELCARD
---
language:
  - ${PIPER_LANGUAGE}
license: mit
pipeline_tag: text-to-speech
tags:
  - piper
  - tts
  - onnx
  - ${LANG_NAME,,}
base_model:
  - rhasspy/piper-voices
library_name: onnx
widget:${WIDGET_YAML}
---

# Piper TTS -- ${LANG_NAME} (${LANG_LOCALE}) ${PIPER_QUALITY}

A [Piper](https://github.com/rhasspy/piper) text-to-speech voice for ${LANG_NAME}, exported as ONNX.

## Model Details

| | |
|---|---|
| **Language** | ${LANG_NAME} (${LANG_LOCALE}) |
| **Quality** | ${PIPER_QUALITY} |
| **Base model** | Fine-tuned from ${BASE_CHECKPOINT_NAME} (\`${BASE_CHECKPOINT_LANG}\`) via [rhasspy/piper-checkpoints](https://huggingface.co/datasets/rhasspy/piper-checkpoints) |
| **Sample rate** | ${PIPER_SAMPLE_RATE} Hz |
| **Format** | ONNX |

## Usage

### With Piper CLI

\`\`\`bash
pip install piper-tts
echo 'your text here' | piper --model ${ONNX_NAME}.onnx --output_file output.wav
\`\`\`

### With NVDA

Download both files and place them in NVDA's Piper voices directory:
- \`${ONNX_NAME}.onnx\`
- \`${ONNX_NAME}.onnx.json\`

### Programmatic (Python)

\`\`\`python
import subprocess
text = "your text here"
subprocess.run(
    ["piper", "--model", "${ONNX_NAME}.onnx", "--output_file", "output.wav"],
    input=text.encode(),
)
\`\`\`

## Files

| File | Description |
|------|-------------|
| \`${ONNX_NAME}.onnx\` | ONNX model |
| \`${ONNX_NAME}.onnx.json\` | Piper config (phoneme map, sample rate, etc.) |
| \`samples/\` | Audio samples generated by this model |

## Training

Trained using the [Piper TTS Training Pipeline](https://github.com/nicpottier/piper-tts-training). Fine-tuned from the ${BASE_CHECKPOINT_NAME} (\`${BASE_CHECKPOINT_PATH}\`) checkpoint.
MODELCARD

echo "Generated model card."

# --- Step 8: Upload ---
echo ""
echo "Uploading to ${HF_REPO} ..."
echo ""
huggingface-cli upload "${HF_REPO}" "${UPLOAD_DIR}" . --commit-message "Upload ${LANG_NAME} Piper TTS model (${PIPER_QUALITY})"

echo ""
echo "=== Published ==="
echo ""
echo "  https://huggingface.co/${HF_REPO}"
echo ""
